# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphViewer = PlotWidget(self.centralwidget)
        self.graphViewer.setGeometry(QtCore.QRect(0, 290, 1281, 621))
        self.graphViewer.setObjectName("graphViewer")
        self.saveButton = QtWidgets.QPushButton(self.graphViewer)
        self.saveButton.setGeometry(QtCore.QRect(1000, 0, 131, 31))
        self.saveButton.setObjectName("saveButton")
        self.clearButton = QtWidgets.QPushButton(self.graphViewer)
        self.clearButton.setGeometry(QtCore.QRect(1150, 0, 131, 31))
        self.clearButton.setObjectName("clearButton")
        self.foldButton = QtWidgets.QPushButton(self.graphViewer)
        self.foldButton.setEnabled(True)
        self.foldButton.setGeometry(QtCore.QRect(1080, 50, 131, 31))
        self.foldButton.setObjectName("foldButton")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(40, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.detrendCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.detrendCheck.setGeometry(QtCore.QRect(40, 260, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.detrendCheck.setFont(font)
        self.detrendCheck.setObjectName("detrendCheck")
        self.offsetText = QtWidgets.QLineEdit(self.centralwidget)
        self.offsetText.setGeometry(QtCore.QRect(120, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.offsetText.setFont(font)
        self.offsetText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offsetText.setObjectName("offsetText")
        self.periodText = QtWidgets.QLineEdit(self.centralwidget)
        self.periodText.setGeometry(QtCore.QRect(120, 100, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.periodText.setFont(font)
        self.periodText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.periodText.setObjectName("periodText")
        self.listOfTransits = QtWidgets.QListWidget(self.centralwidget)
        self.listOfTransits.setGeometry(QtCore.QRect(740, 10, 531, 271))
        self.listOfTransits.setObjectName("listOfTransits")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 40, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 110, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(1130, 240, 131, 31))
        self.deleteButton.setObjectName("deleteButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuGraph = QtWidgets.QMenu(self.menubar)
        self.menuGraph.setObjectName("menuGraph")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDetrend = QtWidgets.QAction(MainWindow)
        self.actionDetrend.setCheckable(True)
        self.actionDetrend.setObjectName("actionDetrend")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuGraph.addAction(self.actionDetrend)
        self.menuInfo.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project Hunter"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.foldButton.setText(_translate("MainWindow", "Fold graph"))
        self.label_1.setText(_translate("MainWindow", "Offset"))
        self.label_2.setText(_translate("MainWindow", "Period"))
        self.detrendCheck.setText(_translate("MainWindow", "Detrend"))
        self.label.setText(_translate("MainWindow", "d"))
        self.label_3.setText(_translate("MainWindow", "d"))
        self.deleteButton.setText(_translate("MainWindow", "Delete entry"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuGraph.setTitle(_translate("MainWindow", "Graph"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDetrend.setText(_translate("MainWindow", "Detrend"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
